# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Title
#'
#' @param d
#' @param nr
#' @param nc
#'
#' @return
#' @export
#'
#' @examples
kdtree_build_intl <- function(d, nr, nc) {
  .Call('_hypervolume_kdtree_build_intl', PACKAGE = 'hypervolume', d, nr, nc)
}

#' Title
#'
#' @param tr
#' @param ptlist
#' @param nr
#' @param nc
#' @param r
#' @param verb
#'
#' @return
#' @export
#'
#' @examples
kdtree_ball_query_multiple <- function(tr, ptlist, nr, nc, r, verb) {
  .Call('_hypervolume_kdtree_ball_query_multiple', PACKAGE = 'hypervolume', tr, ptlist, nr, nc, r, verb)
}

#' Title
#'
#' @param tr
#' @param ptlist
#' @param nr
#' @param nc
#' @param r
#' @param verb
#'
#' @return
#' @export
#'
#' @examples
kdtree_ball_query_id_multiple <- function(tr, ptlist, nr, nc, r, verb) {
  .Call('_hypervolume_kdtree_ball_query_id_multiple', PACKAGE = 'hypervolume', tr, ptlist, nr, nc, r, verb)
}

#' Title
#'
#' @param tr
#' @param pminlist
#' @param pmaxlist
#' @param nr
#' @param nc
#' @param verb
#'
#' @return
#' @export
#'
#' @examples
kdtree_range_query_multiple <- function(tr, pminlist, pmaxlist, nr, nc, verb) {
  .Call('_hypervolume_kdtree_range_query_multiple', PACKAGE = 'hypervolume', tr, pminlist, pmaxlist, nr, nc, verb)
}

#' Title
#'
#' @param Ar
#' @param Br
#'
#' @return
#' @export
#'
#' @examples
fastPdist2 <- function(Ar, Br) {
  .Call('_hypervolume_fastPdist2', PACKAGE = 'hypervolume', Ar, Br)
}
